version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: "mysql -u$MYSQLDB_USER -p$MYSQLDB_ROOT_PASSWORD $MYSQLDB_DATABASE"
      interval: 5s
      timeout: 1s
      retries: 20
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: cookbook-app
    build: ./cookbook
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
              "spring.datasource.username" : "$MYSQLDB_USER",
              "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
              "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "validate"
            }'
  frontend:
    depends_on:
      - backend
    image: cookbook-app-angular-app
    build: ./angular-app/.
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT
